# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='cateogry',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
