# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zz', '0003_auto_20170424_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='num_commitments',
            field=models.IntegerField(null=True),
        ),
    ]
