# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zz', '0004_auto_20170424_2303'),
    ]

