# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zz', '0005_commitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='date_commited',
            field=models.DateField(blank=True, null=True),
        ),
    ]
