# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zz', '0007_habit_category'),
        ('zz', '0004_auto_20170424_2303'),
    ]

    operations = [
    ]
