# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zz', '0008_merge_20170427_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='category',
            field=models.CharField(choices=[('Mental Health', 'Mental Health'), ('Fitness', 'Fitness'), ('Memory', 'Memory'), ('Creativity', 'Creativity'), ('Time Management', 'Time Management'), ('Other', 'Other')], default='mh', max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='num_commitments',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
