# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zz', '0009_auto_20170429_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='num_commitments',
            field=models.IntegerField(default=1),
        ),
    ]
