# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 20:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zz', '0010_auto_20170429_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zz.Habit')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
