# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 20:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zz', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='commitments',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='zz.Habit'),
            preserve_default=False,
        ),
    ]
