# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zz', '0012_merge_20170501_1803'),
    ]

