# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zz', '0012_profile_commitments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='commitments',
        ),
    ]
