# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zz', '0013_remove_profile_commitments'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='commitments',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='zz.Commitment'),
            preserve_default=False,
        ),
    ]
