# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zz', '0005_comment'),
        ('zz', '0015_habit_committers'),
    ]

    operations = [
    ]
