# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zz', '0013_auto_20170501_1807'),
        ('zz', '0016_merge_20170501_1758'),
    ]

    operations = [
    ]
