# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zz', '0017_merge_20170501_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='commitments',
        ),
    ]
